language: go

go:
  - '1.13.x'

services:
  - docker

jobs:
  include:
    - stage: Unit Tests
      script: make unit-test

    - stage: Integration Tests
      before_script:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v0.18.0/operator-sdk-v0.18.0-x86_64-linux-gnu && mv operator-sdk-v0.18.0-x86_64-linux-gnu operator-sdk && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/

      script: make e2e-test
