language: go

go:
  - '1.14.x'

services:
  - docker

jobs:
  include:
    - stage: Unit Tests
      before_script:
        - curl -L https://go.kubebuilder.io/dl/2.3.1/linux/amd64 | tar -xz -C /tmp/ && sudo mv /tmp/kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder
      script: make test

    - stage: Integration Tests
      before_script:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.0.0/operator-sdk-v1.0.0-x86_64-linux-gnu && mv operator-sdk-v1.0.0-x86_64-linux-gnu operator-sdk && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/

      script: make e2e-test
