
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-access-manager-io-v1-RbacDefinition
  failurePolicy: Ignore
  name: rbacdefinition.access-manager.io
  rules:
  - apiGroups:
    - access-manager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - RbacDefinitions
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-access-manager-io-v1-SyncSecretDefinition
  failurePolicy: Ignore
  name: syncSecretdefinition.access-manager.io
  rules:
  - apiGroups:
    - access-manager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - SyncSecretDefinitions
  sideEffects: None
