apiVersion: access-manager.io/v1beta1
kind: RbacDefinition
metadata:
  name: rbac-def1
spec:
  namespaced:
  #   - namespace:
  #       name: velero
  #     bindings:
  #       - roleName: backup-role
  #         kind: Role
  #         subjects:
  #           - name: hd-team
  #             kind: Group
  #           - name: asmiov-team
  #             kind: Group
    - namespaceSelector:
        matchLabels:
          ci: "true"
      bindings:
        - roleName: drone-deploy
          kind: ClusterRole
          subjects:
            - name: default
              namespace: namespace1
              kind: ServiceAccount
  #   - namespaceSelector:
  #       matchLabels:
  #         team/asimov-team: true
  #     bindings:
  #       - roleName: team-binding
  #         kind: ClusterRole
  #         subjects:
  #           - name: asimov-team
  #             kind: Group
  #   - namespaceSelector:
  #       matchLabels:
  #         team/hd-team: true
  #     bindings:
  #       - roleName: team-binding
  #         kind: ClusterRole
  #         subjects:
  #           - name: hd-team
  #             kind: Group
  # cluster:
  #   - clusterRoleName: view
  #     subjects:
  #       - name: admin
  #         kind: Group
