apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: access-manager
  template:
    metadata:
      labels:
        name: access-manager
    spec:
      serviceAccountName: access-manager
      containers:
        - name: access-manager
          # Replace this with the built image name
          image: ckotzbauer/access-manager:latest
          command:
          - access-manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "access-manager"
      imagePullSecrets:
        - name: dockerhub
