apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: access-manager
  template:
    metadata:
      labels:
        name: access-manager
    spec:
      serviceAccountName: access-manager
      containers:
        - name: access-manager
          image: ckotzbauer/access-manager:latest
          imagePullPolicy: IfNotPresent
          command:
          - access-manager
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "access-manager"
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 50m
              memory: 128Mi
          securityContext:
            privileged: false
            runAsUser: 1001
            runAsNonRoot: false
