apiVersion: access-manager.io/v1beta1
kind: SyncSecretDefinition
metadata:
  name: syncsecretdefinition-sample
spec:
  source:
    name: source-secret
    namespace: default
  targets:
  - namespace:
      name: my-product
  - namespaceSelector:
      matchLabels:
        ci: "true"
