name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_ACCESS }}

      - name: Setup Node
        uses: actions/setup-node@v2.3.1
        with:
          node-version: '14'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Setup Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.2
        with:
          version: 3.1.0

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.1'

      - name: Execute Tests
        run: |
          make test
          make e2e-test

      - name: Dockerhub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ckotzbauer/access-manager:${{ github.event.inputs.version }}
            ckotzbauer/access-manager:latest
            ghcr.io/ckotzbauer/access-manager:${{ github.event.inputs.version }}
            ghcr.io/ckotzbauer/access-manager:latest

      - name: Generate changelog
        run: npx @code-chris/changelog-generator --release-version ${{ github.event.inputs.version }} --github-handle ${{ github.repository }} --commit-output commits.md

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: release ${{ github.event.inputs.version }}" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.REPO_ACCESS }}
          branch: master

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: master
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body_path: commits.md
          prerelease: ${{ contains(github.event.inputs.version, 'alpha') || contains(github.event.inputs.version, 'beta') || contains(github.event.inputs.version, 'rc') }}
