name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - name: Setup Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.1
        with:
          version: 2.3.1

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.19.4'

      - name: Execute Tests
        run: |
          make test
          make e2e-test

      - name: Build docker-image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ckotzbauer/access-manager
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildargs: version=${{ github.event.inputs.version }}
          tags: "${{ github.event.inputs.version }},latest"

      - name: Generate changelog
        run: npx @code-chris/changelog-generator --release-version ${{ github.event.inputs.version }} --github-handle ${{ github.repository }} --commit-output commits.md

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: release ${{ github.event.inputs.version }}" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body_path: commits.md
          prerelease: ${{ contains(github.event.inputs.version, 'alpha') || contains(github.event.inputs.version, 'beta') || contains(github.event.inputs.version, 'rc') }}
