name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-goreleaser.yml@0.46.0
    with:
      version: ${{ github.event.inputs.version }}
      docker-platforms: linux/amd64,linux/arm64
      docker-tags: |
        ckotzbauer/access-manager:${{ github.event.inputs.version }}
        ckotzbauer/access-manager:latest
        ghcr.io/ckotzbauer/access-manager:${{ github.event.inputs.version }}
        ghcr.io/ckotzbauer/access-manager:latest
      cosign-repository: ghcr.io/ckotzbauer/access-manager-metadata
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      ghcr-password: ${{ secrets.GHCR_PASSWORD }}
