name: label-issues
on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  label-issues:
    uses: ckotzbauer/actions-toolkit/.github/workflows/label-issues.yml@0.10.1
