name: release

on:
  push:
    branches:
      - 'master'
  release:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          make docker-build
          make docker-push
