name: test

on:
  push:
    branches:
      - '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.2
        with:
          version: 3.1.0

      - name: Execute Tests
        run: make test


  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - "1.23.13"
          - "1.24.7"
          - "1.25.3"
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3.1
        with:
          version: 'v${{ matrix.kubernetes-version }}'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: "v1.6.1"
          install-only: true

      - name: Build binary
        run: make build

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ckotzbauer/access-manager:latest

      - name: Execute Tests
        run: make e2e-test -e K8S_VERSION=${{ matrix.kubernetes-version }}


  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: "v1.6.1"
          install-only: true

      - name: Build binary
        run: make build

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ckotzbauer/access-manager:latest

      - name: Container scan
        uses: ckotzbauer/actions-toolkit/grype@0.25.0
        with:
          scan-target: ckotzbauer/access-manager
          fail-on: "medium"
          config-file: ".github/grype.yaml"
