name: test

on:
  push:
    branches:
      - '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.1
        with:
          version: 2.3.1
      - name: Execute Tests
        run: make test

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - 1.17.11
          - 1.18.8
          - 1.19.1
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v${{ matrix.kubernetes-version }}'
      - name: Execute Tests
        run: make e2e-test -e K8S_VERSION=${{ matrix.kubernetes-version }}
