name: test

on:
  push:
    branches:
      - '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1.2
        with:
          version: 3.1.0
      - name: Execute Tests
        run: make test

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - 1.19.11
          - 1.20.7
          - 1.21.1
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v${{ matrix.kubernetes-version }}'
      - name: Execute Tests
        run: make e2e-test -e K8S_VERSION=${{ matrix.kubernetes-version }}

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker-image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ckotzbauer/access-manager
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "latest"
          no_push: true
      - name: Container scan
        uses: azure/container-scan@v0
        with:
          image-name: ckotzbauer/access-manager
