name: test

on:
  push:
    branches:
      - '**'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - "1.26.6"
          - "1.27.3"
          - "1.28.0"
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/setup-kubectl@v3.2
        with:
          version: 'v${{ matrix.kubernetes-version }}'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: "v1.19.2"
          install-only: true

      - name: Build binary
        run: make build

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            ckotzbauer/access-manager:latest

      - name: Execute Tests
        run: make e2e-test -e K8S_VERSION=${{ matrix.kubernetes-version }}


  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.36.0
    with:
      install-go: true
      go-version: "1.21.0"
      install-goreleaser: true
      install-kubebuilder: true
      build-commands: make build
      test-commands: make test
      build-image: true
      docker-tag: ghcr.io/ckotzbauer/access-manager:latest
      scan-image: true
